############################
# Aparência
############################

# Transparência suave
background_opacity 0.88

# Blur (Wayland/KDE/GNOME)
#background_blur 16

# Padding interno
window_padding_width 10

# Fonte
font_family      FiraCode Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 12.0

# Ligações tipográficas
disable_ligatures never

# Cursor
cursor_shape beam
cursor_blink_interval 0.5
cursor_stop_blinking_after 15

# Tema escuro consistente
foreground #d8dee9
#background #111111

############################
# Performance
############################

repaint_delay 8
input_delay 2
sync_to_monitor yes

############################
# Scroll
############################

scrollback_lines 20000
wheel_scroll_multiplier 5.0

############################
# Bell
############################

enable_audio_bell no
visual_bell_duration 0.0

############################
# Seleção e URLs
############################

copy_on_select yes
strip_trailing_spaces smart
detect_urls yes

############################
# Tabs
############################

tab_bar_style powerline
tab_bar_edge top
tab_bar_align left

tab_bar_min_tabs 1
tab_powerline_style slanted

active_tab_foreground   #1e1e2e
active_tab_background   #89b4fa

inactive_tab_foreground #cdd6f4
inactive_tab_background #313244

############################
# Splits / Layouts
############################

enabled_layouts splits:split_axis=horizontal,stack,tall

map f5 launch --location=vsplit
map f6 launch --location=hsplit

# Fechar o terminal/painel ativo
map f4 close_window

# Criar uma nova aba
map alt+f5 new_tab

# Fechar a aba atual
map alt+f4 close_tab

############################
# Navegation
###########################

# Navegar entre splits/painéis
map ctrl+left neighboring_window left
map ctrl+right neighboring_window right
map ctrl+up neighboring_window up
map ctrl+down neighboring_window down

# Navegar entre abas (pages)
map alt+left previous_tab
map alt+right next_tab

############################
# Qualidade de vida
############################

# Abrir links com Ctrl+Click
mouse_map ctrl+left release grabbed,ungrabbed mouse_handle_click link


# Menos atraso no ESC (Neovim/TMUX)
kitty_mod ctrl+shift

############################
# Wayland
############################

linux_display_server auto
