general {
    disable_loading_bar = true
    grace = 0
    hide_cursor = true
}

background {
    path = /home/predroa/Pictures/wallpaper/kath.png
    blur_passes = 1
    blur_size = 6
}

input-field {
    size = 300, 50
    outline_thickness = 2

    dots_size = 0.2
    dots_spacing = 0.2

    outer_color = rgba(00ffffff)
    inner_color = rgba(000000ff)
    font_color = rgba(ffffffff)

    fade_on_empty = false
    placeholder_text = <span foreground="gray">Senha...</span>
}

label {
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    font_size = 50
    color = rgba(00ffffff)

    position = 0, 80
    halign = center
    valign = center
}
